config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home'
  get 'maps/oscmap'
  root 'maps#oscmap'
  post  'maps/update', to: 'maps#update', as: 'maps_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html:"Hello World"
  end
end

app/controllers/maps_controller.rb
# -*- coding: utf-8 -*-

require 'net/http'
require 'uri'
require 'json'

class MapsController < ApplicationController

    before_action :load_vars

    def oscmap
        p @rakuten_app_id

        @center_lat = 35.6812362
        @center_lon = 139.7671248

        url = URI.parse("https://app.rakuten.co.jp/services/api/Travel/SimpleHotelSearch/20170426?format=json&datumType=1&latitude=" + @center_lat.to_s + "&longitude=" + @center_lon.to_s + "&searchRadius=1&applicationId=" + @rakuten_app_id)
        #puts url
        json = Net::HTTP.get(url)
        result = JSON.parse(json)
        #p result
        @yado_place = []
        @yado_reviewAverage = []
        if result.has_key?('hotels') then
            for hotel in result['hotels'] do
                #p hotel['hotel'][0]['hotelBasicInfo']
                lat = hotel['hotel'][0]['hotelBasicInfo']['latitude']
                lon = hotel['hotel'][0]['hotelBasicInfo']['longitude']
                reviewAverage = hotel['hotel'][0]['hotelBasicInfo']['reviewAverage']

                @yado_place.push([lat, lon])
                if reviewAverage
                    @yado_reviewAverage.push(reviewAverage)
                else
                    @yado_reviewAverage.push(1)
                end
            end
        end
        p @yado_reviewAverage

    end

    def update
        place = params[:data]
        #@results = { :message => place }
        url = URI.parse(URI.encode('https://nominatim.openstreetmap.org/search/' + place + '?format=json&polygon=0&addressdetails=1'))
        json = Net::HTTP.get(url)
        result = JSON.parse(json)

        @center_lat = 35.68
        @center_lon = 139.77

        if result.length > 0 then
            @center_lat = result[0]['lat']
            @center_lon = result[0]['lon']
        end

        url = URI.parse("https://app.rakuten.co.jp/services/api/Travel/SimpleHotelSearch/20170426?format=json&datumType=1&latitude=" + @center_lat.to_s + "&longitude=" + @center_lon.to_s + "&searchRadius=1&applicationId=" + @rakuten_app_id)

        json = Net::HTTP.get(url)
        result = JSON.parse(json)

        @yado_data = []
        if result.has_key?('hotels') then
            for hotel in result['hotels'] do
                #p hotel['hotel'][0]['hotelBasicInfo']
                lat = hotel['hotel'][0]['hotelBasicInfo']['latitude']
                lon = hotel['hotel'][0]['hotelBasicInfo']['longitude']

                @yado_data.push([lat, lon])
            end
        end

        @results = {
            'lat' => @center_lat, 'lon' => @center_lon, 'yado_data' => @yado_data
        }

        render json: @results, status: 200
    end

    private
    def load_vars
        @rakuten_app_id = ENV['RAKUTEN_APP_ID']
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/oscmap.html.erb
<% provide(:title, "Gra-Navi") %>
<h1>Gra-Navi Top</h1>

<!-- <form id="form" action="#" onsubmit="return false;">
  <input id="sbox" name="s" type="text" placeholder="キーワードを入力" />
  <input id="sbtn" type="submit" value="検索" />
</form> -->

<div id="request_ajax_update" >
  <%= form_with url: maps_update_path, id: 'form', remote: false do |form| %>
    <%= form.text_field :data, id: 'sbox' %>
    <%= form.submit '検索する', id: 'sbtn' %>
  <% end %>
</div>

<div id="result"></div>

<div id="map_wrapper">
  <div id="map" class="box"></div>
</div>

<%=
map(:center => {
    :latlng => [@center_lat, @center_lon],
    :zoom => 16,
})
%>

<script>
const yado_latlng = <%= @yado_place %>;
const yado_reviewAverage = <%= @yado_reviewAverage %>

for(var array_count = 0; array_count < yado_latlng.length; array_count++){
  const d = Math.pow(yado_reviewAverage[array_count], 8)/1000 + 10;
  var icon = L.divIcon({
    className: 'marker',
    iconSize: [d, d],
    html: 'a'
  });
  L.marker(yado_latlng[array_count], {icon: icon, riseOnHover: true, opacity: 0.3}).addTo(map);
}
</script>
<script>
  $(function() {
    $('#request_ajax_update').on('ajax:success', function(event) {
      const data = event.detail[0];
      const lon = data['lon'];
      const lat = data['lat'];

      document.getElementById('map_wrapper').innerHTML = "<div id='map' class='box' style=''></div>";

      if (map != undefined) { map.remove(); }

      var map = L.map('map').setView([lat,lon], 16);

      const tileLayer = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{
        attribution: '© <a href="http://osm.org/copyright">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
      });

      const yado_latlng = data['yado_data'];

      for(var array_count = 0; array_count < yado_latlng.length; array_count++){
        L.marker(yado_latlng[array_count]).addTo(map);
      }

      tileLayer.addTo(map);
      $('#result').text(data['lat'] + ':' + data['lon']);
    });

    $('#request_ajax_update').on('ajax:error', function(event) {
      alert("失敗！");
    });
  });
</script>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</p>